### ISSUE TITLE
feat: Add Payable Transactions through Soroban

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/DemocraChain#16]
# Add Payable Transactions through Soroban

## TODO

- [ ] Write Contract Function for Payable Transactions
- [ ] Integrate with Frontend
- [ ] Add Suitable Fields for Transaction on Frontend
