### ISSUE TITLE
test: Test the Rewitten Context

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/DemocraChain#4]
# Test the Rewitten Context

## TODO

- [x] Owner Only
- [x] Set Vote Time
- [x] Fetch Vote Time
- [x] Fetch Single Voter
- [x] Fetch Single Candidate
- [x] Register Voter
- [x] Register Candidate
- [x] Fetch Registered Candidates
- [x] Fetch Registered Voters
- [x] Fetch Voters who voted
- [x] Highest Voted Candidates
- [x] Get Winner
- [x] Give Vote
- [x] Reset Contract
- [x] Change Owner
- [x] Update Candidadate
- [x] Update Voter
- [x] Reject Candidate
- [x] Reject Voter
- [x] Approve Candidate
- [x] Approve Voter
